# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('url', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='args_id',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='url_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='configuration',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
