# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160816_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
