# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160816_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='configuration',
            field=models.CharField(default='', max_length=255),
        ),
    ]
